version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./commands:/docker-entrypoint-initdb.d
    networks:
      - go-clean-network

  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - go-clean-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-clean-app
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - 8000:8000
      - 8080:8080
      - 50051:50051
    networks:
      - go-clean-network

networks:
  go-clean-network:
